### PR TITLE
[task6] Implement endpoint to update Interviewer Time Slot beta

### PR DESCRIPTION
**Pull request by Sviat2001**

### CODE REVIEW

**Comment by Wectro20** [comment]
|File|Coverage [12.72%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerTimeSlotController.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/c2a5af9c3f6412a6ce456a776092394dd333761e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontroller%2FInterviewerTimeSlotController.java)|30%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/c2a5af9c3f6412a6ce456a776092394dd333761e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fslot%2FCandidateTimeSlot.java)|23.79%|:green_apple:|
|[InterviewerTimeSlotService.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/c2a5af9c3f6412a6ce456a776092394dd333761e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservice%2FInterviewerTimeSlotService.java)|4.05%|:x:|
|[ApplicationExceptionHandler.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/c2a5af9c3f6412a6ce456a776092394dd333761e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationExceptionHandler.java)|1.8%|:x:|
|[SlotNotFoundException.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/c2a5af9c3f6412a6ce456a776092394dd333761e/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|0%|:x:|

|Total Project Coverage|16.98%|:green_apple:|
|:-|:-:|:-:|

**Comment by Wectro20** [comment]
|File|Coverage [39.78%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerTimeSlotService.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/8852cc717c51f71e1a16a58080e039bf59564781/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservice%2FInterviewerTimeSlotService.java)|77.68%|:green_apple:|
|[InterviewerTimeSlotController.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/8852cc717c51f71e1a16a58080e039bf59564781/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontroller%2FInterviewerTimeSlotController.java)|60%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/8852cc717c51f71e1a16a58080e039bf59564781/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fslot%2FCandidateTimeSlot.java)|23.79%|:green_apple:|
|[ApplicationExceptionHandler.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/8852cc717c51f71e1a16a58080e039bf59564781/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationExceptionHandler.java)|14.97%|:green_apple:|
|[SlotNotFoundException.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/8852cc717c51f71e1a16a58080e039bf59564781/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|0%|:x:|

|Total Project Coverage|38.7%|:green_apple:|
|:-|:-:|:-:|

**Comment by Wectro20** [comment]
|File|Coverage [39.78%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerTimeSlotService.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/f323c7065364d8e6f9ed554f6e2d38f8cdde36a9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservice%2FInterviewerTimeSlotService.java)|77.68%|:green_apple:|
|[InterviewerTimeSlotController.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/f323c7065364d8e6f9ed554f6e2d38f8cdde36a9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontroller%2FInterviewerTimeSlotController.java)|60%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/f323c7065364d8e6f9ed554f6e2d38f8cdde36a9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodel%2Fslot%2FCandidateTimeSlot.java)|23.79%|:green_apple:|
|[ApplicationExceptionHandler.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/f323c7065364d8e6f9ed554f6e2d38f8cdde36a9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationExceptionHandler.java)|14.97%|:green_apple:|
|[SlotNotFoundException.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/f323c7065364d8e6f9ed554f6e2d38f8cdde36a9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|0%|:x:|

|Total Project Coverage|38.7%|:green_apple:|
|:-|:-:|:-:|

**Comment by Wectro20** [comment]
|File|Coverage [57.21%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewerTimeSlotService.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/2a4778ab082208ee8542f331217bc2903cb0ad2c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservice%2FInterviewerTimeSlotService.java)|77.68%|:green_apple:|
|[InterviewerTimeSlotController.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/2a4778ab082208ee8542f331217bc2903cb0ad2c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontroller%2FInterviewerTimeSlotController.java)|60%|:green_apple:|
|[ApplicationExceptionHandler.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/2a4778ab082208ee8542f331217bc2903cb0ad2c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationExceptionHandler.java)|30.46%|:green_apple:|
|[SlotNotFoundException.java](https://github.com/Wectro20/intellistart-java-2022-propositum/blob/2a4778ab082208ee8542f331217bc2903cb0ad2c/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FSlotNotFoundException.java)|0%|:x:|

|Total Project Coverage|44.72%|:green_apple:|
|:-|:-:|:-:|

**Review by Ratchet34702 — APPROVED** [review]
Approved

**Pull request merged**
